use fuse-t

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,8 +35,17 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Install MacFuse
-        run: brew install --cask macfuse
+      - name: Install FUSE-T
+        run: |
+          brew tap macos-fuse-t/homebrew-cask
+          brew install fuse-t
+          if brew list fuse-t &>/dev/null; then
+            echo "FUSE-T was successfully installed"
+          else
+            echo "FUSE-T installation failed"
+            exit 1
+          fi
+        continue-on-error: false
 
       - name: Set up Go
         uses: actions/setup-go@v4
@@ -52,7 +61,7 @@ jobs:
           deno-version: vx.x.x
 
       - name: Test (macOS)
-        run: make test
+        run: sudo -E make test
         env:
           VAL_TOWN_API_KEY: ${{ secrets.VAL_TOWN_API_KEY }}
 
